### ISSUE TITLE
Unexpected behaviour in login callback

### ISSUE THREAD

**Issue by jeffrson** [deepstreamIO/deepstream.io-client-js#492] opened 2019-06-11 15:54 UTC
Hi,

I use deepstream.io;4.0.0 docker image and @deepstream/client from node. The behaviour was the same with v3, though.

Inside the callback of client.login, I cannot set or query records (it seems, nothing happens when setting, query is empty). No error message.

Furthermore, "data" (second parameter) is null. Not empty, but null. Authentication is not enabled. May this be related? It doesn't matter, however, whether I give some user credentials in login ({ type: 'email' ...}

**Comment by yasserf** [comment] 2019-06-12 05:55
Hello! Can you show me your code please?

**Comment by jeffrson** [comment] 2019-06-12 07:03
Yes - sure. I'm sorry - I thought it was obvious...
```
const deepstream = require('@deepstream/client')
const client = deepstream('ws://server:6020');

client.login({
  type: 'email',
  email: 'user@example.com',
  password: 'sesame'
}, (success,data) => {
  if (success) {
    console.log("Success " + data)
    var myRecord = client.record.getRecord( 'test/johndoe' );
    myRecord.set({
      firstname: 'Jane',
      lastname: 'Doe'
    });
    myRecord.set( 'hobbies', [ 'programming', 'riding' ] );

    console.log(myRecord.get())
  } else {
    console.log("Failed")
  }
})

setTimeout(() => {
    var myRecord = client.record.getRecord( 'test/johndoe' );
    console.log(myRecord.get())
/*
    myRecord.set({
      firstname: 'John',
      lastname: 'Doe'
    });
    myRecord.set( 'hobbies', [ 'sailing', 'reading' ] );
*/
    console.log(myRecord.get())
}, 2000)
```
Interestingly, when I run the code a second time, without the set-part in setTimeout it print the data of Jane. For me this is rather unpredictable.

**Comment by yasserf** [comment] 2019-06-12 07:23
Okay so in terms of obviousness, this has nothing to do with the login callback, as the code example you provided is purely around setting/getting records. I'm still confused to what your actual issue is.

One thing I noticed is that you are using getters synchronously on async code. That is meant to be unpredictable behaviour because the server needs to send the data first which is async.

As a general guideline for raising issues, I would recommend always putting what the console.log actually outputs next to the console.log, like such

`console.log(myRecord.get()) // {
      firstname: 'John',
      lastname: 'Doe',
      hobbies: [ 'sailing', 'reading' ]
 }`

Can you please provide an issue with exactly what you expect so that I can help diagnose if this is an issue or if you are using the api incorrectly? Thanks!

**Comment by yasserf** [comment] 2019-06-12 07:26
Also the second parameter for data is only provided if your authentication handler provides clientData, which means you need authentication. Null indicates none, empty indicates explicitly empty. This distinction is important in certain cases.

**Comment by yasserf** [comment] 2019-06-12 07:30
Closing as a duplicate of #493

**Closed by yasserf** 2019-06-12 07:30 UTC
