### ISSUE TITLE
How does Deepstream handle multiple data-providers that match a pattern?

### ISSUE THREAD

**Issue by kolpax** [deepstreamIO/deepstream.io-client-js#137] opened 2016-05-31 13:47 UTC
What happens when multiple servers have the same data-providers for HA or somehow the pattern for multiple data-providers matches the name? Will one win or will both execute?

**Comment by yasserf** [comment] 2016-05-31 14:44
Sorry, what do you mean by 'for HA'?

Currently all providers would be notified once a pattern is matched.

**Comment by kolpax** [comment] 2016-05-31 14:46
@yasserf Sorry, for high availability.

**Comment by kolpax** [comment] 2016-05-31 15:04
@yasserf Shouldn't that work through RCP though?

**Comment by yasserf** [comment] 2016-06-30 18:09
Closing as duplicate of #211

**Closed** 2016-06-30 18:09 UTC
