### ISSUE TITLE
Problems with setData callback

### ISSUE THREAD

**Issue by dargolith** [deepstreamIO/deepstream.io-client-js#466] opened 2018-03-15 18:55 UTC
Subsequent setData calls seem to overwrite eachother's callbacks:
```js
const Deepstream = require('deepstream.io');
const deepstream = require('deepstream.io-client-js');

const server = new Deepstream();
server.start();
const client = deepstream('localhost:6020');
client.login();

const rec = client.record.getRecord('setDataRecord');
rec.whenReady(() => {
  rec.set({ a: 0 });
  rec.discard();
  client.record.setData('setDataRecord', 'a', 1, error => console.log('callback 1', error));
  client.record.setData('setDataRecord', 'b', 1, error => console.log('callback 2', error));
  client.record.setData('setDataRecord', 'c', 1, error => console.log('callback 3', error));
});
```
Output:
`callback 3 null`

**Comment by yasserf** [comment] 2019-06-04 08:33
Is there a related version? This has been fixed in V4 by introducing a write-ack-service that pulls all write ack logic into a single location for easy debugging and flow control.

```
  /**
   * Send message with write ack callback.
   */
  public send (message: Message, callback: WriteAckCallback): void {
    if (this.services.connection.isConnected === false) {
      this.services.timerRegistry.requestIdleCallback(callback.bind(this, EVENT.CLIENT_OFFLINE))
      return
    }
    const correlationId = this.count.toString()
    this.responses.set(correlationId, callback)
    this.services.connection.sendMessage(Object.assign({}, message, { correlationId, action: ACTION_TO_WRITE_ACK[message.action] } ))
    this.count++
  }
```

**Comment by dargolith** [comment] 2019-06-18 13:59
@yasserf Thanks for replying. I'm not sure which version this was since it was around 15 months ago. But I think the version we use (latest npm version, right not 2.3.3) has the same problem. We haven't tried v4 yet, however I'm not entirely following how your code example relates to subsequently writing data to records (my example above)?

I see that the API-docs for v4 is still under construction, but setData is right now available there and that's the method I'm referring to. One would assume that several calls to setData would all be handled properly, otherwise that should probably be explicitly noted in the docs.

Please correct me if I'm mistaken. :)

**Comment by yasserf** [comment] 2019-06-18 16:41
hey @dargolith, yeah sorry about the late reply 😅

Yeah you are right in regards to expected behaviour. There were a few issues around V3 that didn't allow write acks to work as expected, mainly due to relying on the version instead of an explicit correlation id.

I'll reopen this and if I get time try to see if I can fix it up in V3, but will also add a couple tests to make sure it doesn't happen or regress in V4

**Comment by yasserf** [comment] 2019-09-19 12:03
So I don’t think I’ll be fixing this in V3 since the server is now compatible with V3 clients and I would recommend upgrading to the V4 client. The V4 client uses correlation ids so each set is unique, which means this issue shouldn’t occur

**Closed by yasserf** 2019-09-19 12:03 UTC
Labels: v3
