### ISSUE TITLE
UNSOLICITED_MESSAGE when the client is not permitted to get a record snapshot

### ISSUE THREAD

**Issue by MuriloFrade** [deepstreamIO/deepstream.io-client-js#384] opened 2017-06-06 09:03 UTC
Hi!
I am playing with valve permissions and I've found this issue.
I have configured my permissions file to a record called "menu" as follows

![image](https://cloud.githubusercontent.com/assets/4869454/26821069/6ec5282a-4aa5-11e7-9db6-48536dc2542b.png)

and when I try to use **client.record.getRecord('menu')** using an unauthorized user I get the error message **MESSAGE_DENIED: MESSAGE_DENIED,menu,R (R)** which is right. The issue is that when I try to use **client.record.snapshot('menu', callback)** my error message is not the same. In that case it is  
 **UNSOLICITED_MESSAGE: menu (R)**

**Comment by AlexBHarley** [comment] 2017-10-09 15:24
So the errors the server sends the client are completely inconsistent:

snapshot error (record doesn't exist)
```
[ 'SN', 'nonExistantRecord', 'RECORD_NOT_FOUND' ]
```

snapshot permission error
```
[ 'MESSAGE_DENIED', 'only-a-can-read-and-create', 'SN' ]
```

Definitely a server side issue

**Comment by AlexBHarley** [comment] 2017-10-10 08:58
Affects head, snapshot and has operations

**Comment by AlexBHarley** [comment] 2017-10-25 16:22
#325

**Comment by yasserf** [comment] 2017-10-28 17:54
This should have been fixed with the message parser refactor. Can @jshrt confirm please?

**Comment by jshrt** [comment] 2017-10-30 09:50
This issue is sort of half fixed?

There are two version, the consistent error message and the inconsistent one.

If you happen to call `getRecord` before using `snapshot` both error message are `MESSAGE_DENIED`, however if you call `snapshot` and then go call `getRecord`, you receive the error messages as *Murilo* described.

The issue is reproduced in: https://github.com/deepstreamIO/testscripts/blob/master/permissions/inconsistent-err-msg.js

To see the consistent version, use: `$ node script.js --consistent`
To see the inconsistent version, use: `$ node script.js // with or without --inconsistent`

**Comment by yasserf** [comment] 2019-10-07 11:29
This should be fixed now we overhauled the way message errors are done.

**Closed by yasserf** 2019-10-07 11:29 UTC
Labels: bug, to reproduce
