### ISSUE TITLE
multiple record set with same ds_id

### ISSUE THREAD

**Issue by kamerk22** [deepstreamIO/deepstream.io-client-js#406] opened 2017-10-02 13:49 UTC
## Step to produce problem
- Deepstream Server : 3.1.0
- Deepstream Client: 2.3.0

When I set record in rethinkdb it will insert 2 record with same ds_id. And it will add additional filed called id.

![rethinkdb administration console](https://user-images.githubusercontent.com/11503211/31080452-5cca2e46-a7a6-11e7-99eb-889a8518910a.png)

However when I try same setup with Deepstream Server 3.0.0 it's operating normally.
Kindly help asap.

**Comment by vishaljadav24** [comment] 2017-10-02 13:55
Same issue in my Deepstream app.

**Comment by yasserf** [comment] 2017-10-02 20:26
Hey, thanks for raising! We'll take a look into it asap

@AlexBHarley any idea what could have regressed?

**Comment by AlexBHarley** [comment] 2017-10-09 14:13
This could be a similar issue to #369. If so, it is not an issue with deepstream.

However I've tried to reproduce and I am not able to, I have run the following script:

```
const deepstream = require('deepstream.io-client-js')

const client = deepstream('localhost:6020')
const recordName = `collection/my-rec`

client.login()
for (let i = 0; i < 10; i++) {
  client.record.getRecord(`${recordName}-${i}`).set({ hello: Date.now() })
}
```

I then have 10 entries in my rethinkdb collection. Is there anymore info you can provide around this issue?

**Comment by kamerk22** [comment] 2017-10-10 14:34
Step to reproduce

```js
ds.record.getRecord(`user_notification/${deliveryData.user.uuid}`).whenReady((item) => {
    let notificaitons = [];
    let notificationObj = {
        delivery_id: deliveryId,
        type: channel.DELIVERY_STATUS_TYPE.ACCEPT.type,
        status: channel.DELIVERY_STATUS_TYPE.ACCEPT.status,
        timestamp: {
            delivery: deliveryData.timestamp,
            notification: new Date()
        },
        user: user
    }

    if (item._$data.notificaitons !== undefined) {
        notificaitons = [...item._$data.notificaitons, notificationObj];
        item.set({
            notificaitons: notificaitons
        })
    } else {
        notificaitons.push(notificationObj)
        item.set({
            notificaitons: notificaitons
        });
    }
})
```

My use case if I want to check if record is already present if Yes then i want to fetch that record and update an array (push new element in array) then update record itself.
 
But when I do so it will added new record every-time. With newly created field id which is added by rethinkdb as deepstream is trying to add same record with same primary key so it will providing new id.

**Comment by kamerk22** [comment] 2017-10-12 05:16
@AlexBHarley  
Any updates?

**Comment by AlexBHarley** [comment] 2017-10-12 16:49
@kamerk22 hm so at a bit of a loss. Here is the full script I'm using

```
const deepstream = require('deepstream.io-client-js')

const ds = deepstream('localhost:6020')
ds.login()

const deliveryData = {
  user: {
    uuid: Math.random()
  },
  timestamp: Date.now()
}

const channel = {
  DELIVERY_STATUS_TYPE: {
    ACCEPT: {
      type: 'food',
      status: 'pending'
    }
  }
}
const user = 'Jeff'
const deliveryId = 123

ds.record.getRecord(`user_notification/${deliveryData.user.uuid}`).whenReady((item) => {
  console.log('Got record', `user_notification/${deliveryData.user.uuid}`)
  let notificaitons = [];
  let notificationObj = {
    delivery_id: deliveryId,
    type: channel.DELIVERY_STATUS_TYPE.ACCEPT.type,
    status: channel.DELIVERY_STATUS_TYPE.ACCEPT.status,
    timestamp: {
      delivery: deliveryData.timestamp,
      notification: new Date()
    },
    user: user
  }

  if (item._$data.notificaitons !== undefined) {
    notificaitons = [...item._$data.notificaitons, notificationObj];
    item.set({
      notificaitons: notificaitons
    })
  } else {
    notificaitons.push(notificationObj)
    item.set({
      notificaitons: notificaitons
    });
  }
})
```

I don't see any duplicate entries in rethinkdb.

deepstream.io: `3.1.0`
deepstream.io-storage-rethinkdb: `1.0.2`
deepstream.io-client-js: `2.3.0`
RethinkDB: `2.3.5`
macOS: `10.12.6`

Providing an example repo is a pain I understand but it would help.

**Comment by yasserf** [comment] 2019-06-04 08:56
Closing as I can't reproduce, but please reopen if you have more information!

**Closed by yasserf** 2019-06-04 08:56 UTC
Labels: awaiting feedback, bug, to reproduce
