### ISSUE TITLE
Records inserted instead of updated

### ISSUE THREAD

**Issue by valentinvichnal** [deepstreamIO/deepstream.io-client-js#369] opened 2017-04-19 17:01 UTC
When I update records deepstream most of the time updates the same MongoDB document, sometimes however they are inserted as new documents instead of updating the previous document.

After I do the following:
- get() a new empty record, deepstream creates a version 0 document
- then I set() the record with some data
- then I get() this record, set the deleted property to true and set() again
The MongoDB database collection look like this after these steps:
```js
{
	"_id": ObjectId('58f66e5854ab4e3d40895fd5'),
	"__ds": { "_v": 0 },
	"ds_key": "j1nytnma-1imtr2v00bi"
},
{
	"_id": ObjectId('58f66e5854ab4e3d40895fd6'),
	"text": "Hello world!",
	"deleted": false,
	"__ds": { "_v": 1 },
	"ds_key": "j1nytnma-1imtr2v00bi"
},
{
	"_id": ObjectId('58f66e5854ab4e3d40895fd7'),
	"text": "Hello world!",
	"deleted": true,
	"__ds": { "_v": 2 },
	"ds_key": "j1nytnma-1imtr2v00bi"
}
```
Now I have 3 documents all share the same ds_key but with different _id.

This bug happens most of the time when the appropriate MongoDB Collection didn't exists,
but sometimes it occurs when it already exists with documents in it.
I don't know whether the MongoDB storage connector do this, or something else.
But when I request this record I always get back the document with the highest version number.

**Comment by AlexBHarley** [comment] 2017-10-09 12:57
Did a bit of digging into this, it occurs when creating a new collection and then doing subsequent writes to that collection.

In short, we don't wait for the callback of `updateOne` in the mongodb driver, so when we do a write, mongo does not know that the previous write has gone through. Because we pass an `upsert: true` flag, a new entry in the collection is created.

**Comment by AlexBHarley** [comment] 2017-10-09 13:08
Can reproduce with the following script:

```
const mongoClient = require('mongodb').MongoClient

mongoClient.connect('mongodb://localhost:27017/deepstream-mongo-test', (err, db) => {
  const collection = db.collection('yourCollection')
  collection.ensureIndex({ ds_key: 1 })
  const key = 'my-key'
  const value = {
    hello: Date.now(),
    ds_key: key,
    __ds: {
      _v: 0
    }
  }
  collection.updateOne({ ds_key: key }, value, { upsert: true }, () => {})
  value.hello = Date.now()
  value.__ds._v = 1
  collection.updateOne({ ds_key: key }, value, { upsert: true }, () => {} )
})
```

Results in  the following in the db when run for the first time

```
{ "_id" : ObjectId("59db743a8fe106d788de5efc"), "hello" : 1507554362266, "ds_key" : "my-key", "__ds" : { "_v" : 0 } }
{ "_id" : ObjectId("59db743a8fe106d788de5efd"), "hello" : 1507554362268, "ds_key" : "my-key", "__ds" : { "_v" : 1 } }
```

Closing this because it appears to not be an issue with deepstream, but the mongodb driver

**Closed by AlexBHarley** 2017-10-09 13:08 UTC
Labels: bug, in progress
