### ISSUE TITLE
Records or saved 2 times with getRecord and set

### ISSUE THREAD

**Issue by BezMaster** [deepstreamIO/deepstream.io-client-js#349] opened 2017-03-17 13:55 UTC
I work with a rethinkDB connector.
   1) I start my rethinkdb
   2) I start my deepstream server with node js script launcher
   3) I start my deepstream.client on an other node js script.

All works fine.

But when i launch a simple sample from the nodejs deepstream.client script like that
```
        var uid = ds.getUid();
	var newUserID = 'Users/'+uid;
	
	var newMessage = ds.record.getRecord( newUserID);
	newMessage.whenReady( ( record) => {
		record.set( {username : 'Luke'} );
	});
```
My record is saved 2 times with the same ds_id.
the first with undefined fields
the second with the object contains in the set function

Could you help me please ?

**Comment by datasage** [comment] 2017-03-26 18:13
There are two write operations with getRecord and then again with set. This is likely an issue with the storage connector rather than the client itself.

**Comment by ronag** [comment] 2017-03-26 18:17
If the record does not exists deepstream will create an empty record first. This is as designed.

**Comment by yasserf** [comment] 2017-03-26 20:30
@datasage Is correct. Getting a record is an upsert by default, meaning if it doesn't exist, an empty object is created. 
```
//  creates record
var newMessage = ds.record.getRecord( newUserID);

// record was initialized as {}
newMessage.whenReady( ( record) => {
  // record is updated with 'Luke'
  record.set( {username : 'Luke'} );
});
```

**Comment by BezMaster** [comment] 2017-03-27 08:12
First, Thx for your help ;)

@datasage. I think it's not the rethink connector because it works fine in the same condition from an html page. i think it's only du to the deepstream.io-client-js on node js.

1 ) With the deepstream.io-client-js ( **HTML version** ) _it works fine_
- deepstream.io-client-js 2.1.2 ( HTML version )
- rethinkdb 2.3.5
- deepstream 2.1.3

When i work in this context i have the correct behaviour. it's OK

```
//  creates record with data {}
var newMessage = ds.record.getRecord( newUserID);

// record created and set in db as {}
newMessage.whenReady( ( record) => {
  // record is updated with 'Luke' in db
  record.set( {username : 'Luke'} );
});
```
Next this steps i have only one record updated in rethindb and it's the good behaviour for me.


2 ) BUT i observe a difference with the deepstream.io-client-js ( **Npm  node js version** ) _it does not work_.

When i use the deepstream.io-client-js 2.1.2  from node js, I dont have the same behaviour unfortunately
- i start the same rethinkdb 2.3.5
- the same deepstream server 2.1.3
- node 6.10

```
//  creates record with data {} its OK
var newMessage = ds.record.getRecord( newUserID);

// record created and set in db as {}
newMessage.whenReady( ( record) => {
  // record is NOT updated with 'Luke' in db. It creates another ( a new ) record with the same ds_id.
  record.set( {username : 'Luke'} );
});
```

Next this steps, i have an empty record with a ds_id in database
and another record with the same ds_id and data. 

I think it's a bug in nodejs condition

Do you see what i mean ?

**Comment by yasserf** [comment] 2017-04-08 15:57
Would you be able to give me a repo or zip file to recreate and fix the issue?

**Comment by BezMaster** [comment] 2017-04-10 10:20
[deepServer2.zip](https://github.com/deepstreamIO/deepstream.io-client-js/files/909711/deepServer2.zip)

Sorry for my basics explanations , but i want to be sure we make the same thinks
Here you can find my instructions to reproduce this bug

1) Start your rethinkdb server with the following command
rethinkdb.exe --bind all --http-port 9090

2) In an oher terminal start the deepstream server with the rethinkdbconnector
npm install
node server_ws.js

3) In an other terminal start the express Server with the deepClient.js
node server_bug.js

4) Write the following URL in your webbrowser
http://localhost:3000

5) Press the addNewUser Button 

6) Inpect your rethinkdb with
http://localhost:9090/#dataexplorer
	
7) Put the following rethinkdb request in the input 
r.db('deepstream').table('Users')
	
8) Run it
	
9) And then you can find two records.

Best regards ;)

**Comment by yasserf** [comment] 2017-04-11 11:15
This is great, thank you!

**Comment by yasserf** [comment] 2017-04-12 22:23
@AlexBHarley @mrby I'm bumping this priority up since we have a way to replicate issue.

@AlexBHarley you comfortable looking into this?

**Comment by AlexBHarley** [comment] 2017-04-18 14:23
@BezMaster, I've tried to recreate this using zip file you've given us, and haven't been able to.

The following is what my db looks like after adding 3 users via your script, and running the following script once:

```
const deepstream = require('deepstream.io-client-js')

const client = deepstream('localhost:6020')

client.login()

var uid = client.getUid();
var newUserID = 'Users/'+uid;

var newMessage = client.record.getRecord( newUserID);
newMessage.whenReady( ( record) => {
  record.set( {username : 'Luke'} );
});
```

![screen shot 2017-04-18 at 16 20 50](https://cloud.githubusercontent.com/assets/11168524/25135616/2c6d3f12-2453-11e7-8294-c8b27aab9c5f.png)

As you can see, no duplicate entries.

Could you please try again with the latest versions of the server and client? I can then take a closer look.

**Comment by valentinvichnal** [comment] 2017-04-19 17:18
#369 Probably related

**Comment by BezMaster** [comment] 2017-04-20 12:55
@AlexBHarley 

- What is your deepstream server version ?

- Do you exactly follow me instructions ?

Today 20/04/2016, i made the test again and the problem still here :(

Because when i install deepstream server from npm install, i get the deepstream server v 2.1.6.

I know that the last official version is the 2.2.0 but from NPM the last is 2.1.6. Is it the reason why we have a difference ?

**Comment by AlexBHarley** [comment] 2017-04-20 14:52
@BezMaster

- I tried with both 2.1.3 as per your instructions and 2.2.0
- I followed them to a t
- The zip worked perfectly fine.

Looks like there was an issue publishing, but 2.2.0 is on NPM now

**Comment by yasserf** [comment] 2017-06-29 09:03
Closing as fixed, please let us know if otherwise

**Closed** 2017-06-29 09:03 UTC
Labels: awaiting feedback, ready
