### ISSUE TITLE
sendSetData not defined

### ISSUE THREAD

**Issue by jshrt** [deepstreamIO/deepstream.io-client-js#443] opened 2017-12-04 17:20 UTC
I've ran into this error after having installed `postgres` storage connector for the server, played with it for a while, and then commented it out of the plugins section.

However, doing the steps above does not reproduce the error. (_will update the steps when successfully reproduced_)

````
   this.sendSetData(recordName, version, { data, callback: this.onRecordUpdated })
         ^
TypeError: this.sendSetData is not a function
    at Storage.sendUpdatedData (/home/jshrt/Workspace/projects/deepstream/io/v4-test/node_modules/deepstream.io-client-js/src/record/record-handler.ts:433:10)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)```
```

**Comment by AlexBHarley** [comment] 2017-12-12 09:45
This is due to a missing `bind`. Will push a fix soon

**Comment by AlexBHarley** [comment] 2017-12-12 10:39
Script to reproduce

```
const deepstream = require('deepstream.io-client-js')
const BBPromise = require('bluebird').Promise
const server = require('./server')

const run = async () => {
  await server.start()

  const client = deepstream('localhost:6020', {
    reconnectIntervalIncrement: 100,
    maxReconnectInterval: 1000,
    maxReconnectAttempts: 999,
  })

  await client.login({})

  const record = client.record.getRecord('test')
  await record.whenReady()

  await server.stop()

  await BBPromise.delay(1000)

  record.set({ hello: 'there' })

  await BBPromise.delay(1000)

  record.discard()

  await BBPromise.delay(1000)

  await server.start()

  const result = await client.record.snapshot('test')
}

run()
```

**Comment by AlexBHarley** [comment] 2017-12-12 11:10
Fixed in v4. @jshrt can you confirm

**Closed by AlexBHarley** 2017-12-12 11:10 UTC
Labels: bug, to reproduce

**Comment by jshrt** [comment] 2017-12-12 15:30
Verified, it is fixed. Thanks Alex!
